In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline

In [11]:
df = pd.read_csv('cheating_detection_dataset_7.csv')
df
df = df.drop(columns = ['participant_id','competition_id'])
df

,total_submissions,active_days_pct,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,submissions_pre_jump,submissions_post_jump,leap_size,post_jump_score_repetition,quiz_participation_pct,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate,archetype
0,4,40.0,1.000000,0.333333,0.333333,0,0.910711,0.869639,1.065738,0.041072,...,1,3,0.119495,0.418684,60.0,17,4.250000,2.428571,0.750,hardworker
1,4,30.0,1.333333,0.000000,1.000000,1,1.200012,1.112830,1.287193,0.087181,...,4,0,0.000000,0.000000,80.0,18,4.500000,2.000000,0.500,consistent_late_breakthrough
2,18,30.0,6.000000,0.000000,0.666667,0,0.561328,0.512454,0.615423,0.048873,...,2,16,0.063731,0.000000,60.0,10,0.555556,1.428571,0.667,late_joiner_dangerous
3,21,70.0,3.000000,1.333333,0.666667,3,0.592643,0.358047,2.260090,0.234596,...,8,13,1.667447,0.722339,30.0,2,0.095238,0.500000,0.810,consistent_late_breakthrough
4,27,60.0,4.500000,0.666667,1.666667,3,0.622750,0.440728,1.029055,0.182022,...,3,24,0.486757,0.006387,40.0,7,0.259259,1.400000,0.815,consistent_ai_leap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5184,17,30.0,5.666667,0.000000,5.000000,2,0.611877,0.435450,2.390095,0.176426,...,1,16,1.685680,0.000000,60.0,2,0.117647,0.285714,0.765,late_joiner_dangerous
5185,16,20.0,8.000000,0.000000,2.000000,0,0.591978,0.510059,2.118979,0.081918,...,1,15,1.380856,0.098688,50.0,7,0.437500,1.166667,0.625,late_joiner_dangerous
5186,2,20.0,1.000000,0.000000,0.000000,0,1.158344,1.122809,1.193880,0.035536,...,2,0,0.000000,0.000000,70.0,21,10.500000,2.625000,1.000,hardworker
5187,27,50.0,5.400000,5.666667,0.666667,0,1.575702,0.580214,2.410464,0.995487,...,20,7,1.816358,0.866817,50.0,16,0.592593,2.666667,0.815,ai_dump_sincere_start
5188,14,20.0,7.000000,0.000000,0.000000,0,0.587242,0.531215,2.201847,0.056027,...,1,13,1.476117,0.034786,20.0,9,0.642857,3.000000,0.500,late_joiner_dangerous

In [12]:
df.describe()

,total_submissions,active_days_pct,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,time_to_best_score_hours,submissions_pre_jump,submissions_post_jump,leap_size,post_jump_score_repetition,quiz_participation_pct,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate
count,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,...,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000,5189.000000
mean,17.038158,59.531702,2.934630,1.253806,1.862530,2.102139,0.759614,0.548847,1.549188,0.210768,...,107.777613,6.557140,10.481018,0.767693,0.293083,57.795336,17.875506,2.453407,2.991224,0.730516
std,10.522569,27.254766,1.427655,1.088662,1.503640,2.546025,0.289485,0.211192,0.672120,0.232605,...,74.310497,6.694316,8.670279,0.659607,0.343402,17.885411,11.138415,4.205802,2.594114,0.154997
min,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.394673,0.300000,0.433878,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.013699,0.090909,0.000000
25%,8.000000,40.000000,2.000000,0.333333,0.666667,0.000000,0.586992,0.433466,0.927693,0.101154,...,35.296754,2.000000,4.000000,0.222899,0.000000,50.000000,9.000000,0.411765,1.250000,0.650000
50%,16.000000,60.000000,2.666667,1.000000,1.666667,1.000000,0.664069,0.499922,1.304325,0.146750,...,110.323553,4.000000,8.000000,0.423486,0.097405,60.000000,17.000000,1.000000,2.400000,0.750000
75%,23.000000,80.000000,3.500000,2.000000,2.666667,3.000000,0.793056,0.574721,2.264304,0.210703,...,173.942939,9.000000,16.000000,1.467803,0.600896,70.000000,26.000000,2.400000,4.000000,0.826000
max,75.000000,100.000000,10.000000,6.000000,9.666667,10.000000,2.430249,2.430249,2.600000,1.441568,...,238.946767,68.000000,63.000000,2.241050,1.000000,100.000000,46.000000,46.000000,39.000000,1.000000

In [ ]:
df

X = df.drop(columns = ['archetype'])
y = df['archetype']

from sklearn.model_selection import train_test_split


d = {x : y for x, y in zip(['hardworker', 'benchmark_tweaker', 'daily_sprinter',
       'consistent_late_breakthrough', 'low_interest_quitter',
       'consistent_ai_leap', 'ai_dump_sincere_start',
       'late_joiner_dangerous', 'pure_ai_quick_dump'], [0, 1, 2, 3, 4, 5, 6, 7, 8])}

display(d)
y = y.map(d)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, shuffle =True)

# train_df = df.copy()
# df_0 = train_df[train_df['Diabetes_binary'] == 0]
# df_1 = train_df[train_df['Diabetes_binary'] == 1]

# df_1 = df_1.sample(len(df_0), replace = True, random_state = 42)

# train_df = pd.concat([df_0, df_1])
# train_df = train_df.sample(frac= 1, random_state = 42)
# # train_df['row_id'] = train_df.index
# # train_df = train_df.drop(columns = ['row_id'])

# X_train = train_df.drop('Diabetes_binary', axis=1)
# y_train = train_df['Diabetes_binary']
# y_train = pd.get_dummies(y_train, dtype = int).values

{'hardworker': 0,
 'benchmark_tweaker': 1,
 'daily_sprinter': 2,
 'consistent_late_breakthrough': 3,
 'low_interest_quitter': 4,
 'consistent_ai_leap': 5,
 'ai_dump_sincere_start': 6,
 'late_joiner_dangerous': 7,
 'pure_ai_quick_dump': 8}

In [14]:
from sklearn.utils.class_weight import compute_sample_weight

In [15]:
# display(X_train)
y_train = pd.DataFrame({
    'archetype' : y_train
})
train_df = pd.concat([X_train, y_train], axis = 1)
# df_0 = train_df[train_df['cheated'] == 0]
# df_1 = train_df[train_df['cheated'] == 1]
sample_weights = compute_sample_weight('balanced', y_train)

# df_1 = df_1.sample(len(df_0), replace = True, random_state = 42)

# train_df = pd.concat([df_0, df_1])
# train_df = train_df.sample(frac= 1, random_state = 42)


X_train = train_df.drop('archetype', axis=1)
y_train = train_df['archetype']




# y_train = pd.get_dummies(y_train, dtype = int).values
display(X_train, y_train)
display(y_train.value_counts())

,total_submissions,active_days_pct,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,time_to_best_score_hours,submissions_pre_jump,submissions_post_jump,leap_size,post_jump_score_repetition,quiz_participation_pct,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate
975,15,50.0,3.000000,2.666667,0.666667,5,1.598561,0.398766,2.298419,1.199795,...,225.436843,11,4,1.663022,0.848916,60.0,11,0.733333,1.571429,0.733
814,18,80.0,2.250000,0.333333,2.333333,5,0.676273,0.501529,0.905144,0.174745,...,77.181817,7,11,0.358188,0.000000,30.0,23,1.277778,5.750000,0.778
203,16,70.0,2.285714,1.333333,3.000000,1,0.584375,0.501055,0.812892,0.083320,...,40.695089,15,1,0.220729,0.000000,50.0,15,0.937500,2.500000,0.750
4016,9,60.0,1.500000,1.333333,0.666667,2,0.604174,0.387246,0.969069,0.216928,...,209.686799,5,4,0.438381,0.486437,50.0,4,0.444444,0.666667,0.667
279,37,100.0,3.700000,1.666667,2.000000,8,0.558019,0.430559,1.091890,0.127460,...,151.367865,27,10,0.432234,0.574378,70.0,9,0.243243,1.125000,0.676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,10,60.0,1.666667,0.000000,0.666667,2,0.831771,0.601030,1.165250,0.230741,...,53.273397,3,7,0.316047,0.076800,50.0,30,3.000000,5.000000,0.700
354,15,60.0,2.500000,1.000000,0.333333,2,0.664017,0.558549,0.895898,0.105468,...,131.820521,1,14,0.332499,0.000000,90.0,20,1.333333,2.000000,0.800
2125,23,90.0,2.555556,1.333333,2.333333,4,0.684727,0.513773,0.946378,0.170954,...,194.903979,18,5,0.256464,0.768385,60.0,27,1.173913,3.857143,0.739
4200,6,30.0,2.000000,0.000000,1.000000,0,0.727627,0.515871,0.969195,0.211756,...,66.811806,5,1,0.226704,0.000000,60.0,16,2.666667,2.285714,0.833
1906,1,10.0,1.000000,0.000000,0.000000,0,0.904820,0.904820,0.904820,0.000000,...,0.000000,1,0,0.000000,0.000000,50.0,39,39.000000,6.500000,1.000

975     6
814     0
203     0
4016    3
279     0
       ..
102     0
354     0
2125    0
4200    0
1906    0
Name: archetype, Length: 4151, dtype: int64

archetype
0    1464
1     605
2     490
7     370
6     338
5     254
4     250
3     202
8     178
Name: count, dtype: int64

In [16]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.5)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)

In [17]:


import optuna
from sklearn.metrics import f1_score, classification_report
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

# def objective(trial):

#     param = {
#         'objective' : 'multi:softprob',
#         'num_class' : 9,
#         'eval_metric' : 'mlogloss',
#         'n_estimators': trial.suggest_int('n_estimators', 300, 1200),
#         'max_depth': trial.suggest_int('max_depth', 3, 10),
#         'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
#         'subsample': trial.suggest_float('subsample', 0.4, 1.0),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
#         'min_child_weight': trial.suggest_int('min_child_weight', 1, 30),
#         'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
#         'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
#         'gamma': trial.suggest_float('gamma', 1e-3, 5.0, log=True),
#         'random_state': 42,
#         'n_jobs': -1
#     }
#     cv = StratifiedKFold(n_splits= 5, shuffle = True, random_state= 42)
#     scores = cross_val_score(
#         estimator = XGBClassifier(**param),
#         X= X_train, y = y_train, cv = cv,
#         scoring='f1_macro',
#         params = {'sample_weight' : sample_weights},
#         n_jobs = -1
#     )

#     return scores.mean()

# study = optuna.create_study(direction='maximize', study_name="XGBoost_CV")
# study.optimize(objective, n_trials=10, show_progress_bar=True)



# print(f"Best CV f1 score: {study.best_value}")

In [18]:
x1 = {'n_estimators': 957, 'max_depth': 10, 'learning_rate': 0.010489050210581588, 'subsample': 0.8816721785062149, 'colsample_bytree': 0.9393240336036071, 'min_child_weight': 1, 'reg_alpha': 0.029288256542840854, 'reg_lambda': 0.0033822170961102394, 'gamma': 0.5239400402156534}
xgb = XGBClassifier(**(x1))
xgb.fit(X_train, y_train, sample_weight=sample_weights)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9393240336036071, device=None,
              early_stopping_rounds=None, enable_categorical=True,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=0.5239400402156534, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.010489050210581588,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=957, n_jobs=None,
              num_parallel_tree=None, ...)

In [19]:
y_pred = xgb.predict(X_test)
f1_score_xgb = f1_score(y_test,y_pred, average='macro')
display(f1_score_xgb)
print(classification_report(y_test, y_pred))

0.8270306250604021

              precision    recall  f1-score   support

           0       0.85      0.89      0.87       366
           1       0.96      1.00      0.98       151
           2       0.98      0.98      0.98       123
           3       0.83      0.69      0.75        51
           4       0.88      0.95      0.91        62
           5       0.41      0.25      0.31        64
           6       1.00      1.00      1.00        84
           7       0.86      0.86      0.86        93
           8       0.73      0.82      0.77        44

    accuracy                           0.87      1038
   macro avg       0.83      0.83      0.83      1038
weighted avg       0.86      0.87      0.87      1038

In [20]:
importance = pd.DataFrame({
    'Feature' : X_train.columns,
    'Importance' : xgb.feature_importances_
})

importance = importance.sort_values(by = 'Importance', ascending= False)
display(importance)

                        Feature  Importance
1               active_days_pct    0.100123
26          rank_to_submissions    0.075552
9                gap_median_top    0.074924
7                     top_score    0.068513
3   submission_avg_initial_days    0.050125
11     peak_submissions_per_day    0.049889
22                    leap_size    0.048593
14       top_score_on_peak_hour    0.048342
6                  median_score    0.047770
19     time_to_best_score_hours    0.041817
0             total_submissions    0.039442
23   post_jump_score_repetition    0.037714
17       above_below_claude_min    0.027993
24       quiz_participation_pct    0.024897
18              score_time_corr    0.023497
16          user_min_score_diff    0.022313
2           submissions_per_day    0.021866
8                  lowest_score    0.020186
5               submissions_end    0.020070
10               gap_lowest_top    0.019196
20         submissions_pre_jump    0.018694
27   rank_to_quiz_participation    0.017513
25                   final_rank    0.016307
28             description_rate    0.016009
13    peak_submissions_per_hour    0.014719
21        submissions_post_jump    0.014651
4           avg_submissions_mid    0.014083
12        top_score_on_peak_day    0.013987
15             claude_min_score    0.011211

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
# def objective(trial):

#     param = {

#         'max_depth': trial.suggest_int('max_depth', 3, 10),
#         'criterion' : trial.suggest_categorical("criterion", ['gini', 'entropy']),
#         'min_samples_split' : trial.suggest_int("min_samples_split", 2, 20),
#         'min_samples_leaf' : trial.suggest_int("min_samples_leaf", 1 , 20),
#         'random_state': 42
#     }
#     cv = StratifiedKFold(n_splits= 5, shuffle = True, random_state= 42)
#     scores = cross_val_score(
#         estimator = DecisionTreeClassifier(**param),
#         X= X_train, y = y_train, cv = cv,
#         scoring='f1_macro',
#         n_jobs = -1
#     )

#     return scores.mean()

# study = optuna.create_study(direction='maximize', study_name="DT_CV")
# study.optimize(objective, n_trials=50, show_progress_bar=True)



# print(f"Best CV f1 score: {study.best_value}")

In [23]:
d1 = {'max_depth': 10, 'criterion': 'entropy', 'min_samples_split': 5, 'min_samples_leaf': 12}
d1

dt = DecisionTreeClassifier(**(d1))
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_leaf=12,
                       min_samples_split=5)

In [24]:
y_pred = dt.predict(X_test)
# display(y_pred)
f1_score_dt = f1_score(y_test,y_pred, average='macro')
display(f1_score_dt)
print(classification_report(y_test, y_pred))

0.7452977576235162

              precision    recall  f1-score   support

           0       0.77      0.90      0.83       366
           1       0.95      0.93      0.94       151
           2       0.94      0.90      0.92       123
           3       0.91      0.61      0.73        51
           4       0.79      0.90      0.84        62
           5       0.23      0.08      0.12        64
           6       0.93      0.95      0.94        84
           7       0.77      0.77      0.77        93
           8       0.68      0.57      0.62        44

    accuracy                           0.82      1038
   macro avg       0.77      0.74      0.75      1038
weighted avg       0.80      0.82      0.80      1038

In [25]:
!pip install dtreeviz

Requirement already satisfied: dtreeviz in /usr/local/lib/python3.12/dist-packages (2.3.2)
Requirement already satisfied: graphviz>=0.9 in /usr/local/lib/python3.12/dist-packages (from dtreeviz) (0.21)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from dtreeviz) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from dtreeviz) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from dtreeviz) (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from dtreeviz) (3.10.0)
Requirement already satisfied: colour in /usr/local/lib/python3.12/dist-packages (from dtreeviz) (0.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtreeviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->dtreeviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->dtreeviz) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->dtreeviz) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->dtreeviz) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->dtreeviz) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->dtreeviz) (1.17.0)

In [26]:
import graphviz.backend as be

In [27]:
import dtreeviz
from IPython.display import Image , display_svg, SVG

In [28]:
# viz_model = dtreeviz.model(
#     dt,
#     X_train, y_train, target_name='archetype',
#     feature_names= X_train.columns.tolist(),
#     class_names= ['hardworker', 'benchmark_tweaker', 'daily_sprinter',
#        'consistent_late_breakthrough', 'low_interest_quitter',
#        'consistent_ai_leap', 'ai_dump_sincere_start',
#        'late_joiner_dangerous', 'pure_ai_quick_dump']
# )
# viz = viz_model.view()
# viz

In [29]:
# path = viz_model.view(x=X_train.iloc[0], show_just_path= True)
# path

In [30]:
# print(viz_model.explain_prediction_path(X_train.iloc[1]))

In [31]:
df.columns

Index(['total_submissions', 'active_days_pct', 'submissions_per_day',
       'submission_avg_initial_days', 'avg_submissions_mid', 'submissions_end',
       'median_score', 'top_score', 'lowest_score', 'gap_median_top',
       'gap_lowest_top', 'peak_submissions_per_day', 'top_score_on_peak_day',
       'peak_submissions_per_hour', 'top_score_on_peak_hour',
       'claude_min_score', 'user_min_score_diff', 'above_below_claude_min',
       'score_time_corr', 'time_to_best_score_hours', 'submissions_pre_jump',
       'submissions_post_jump', 'leap_size', 'post_jump_score_repetition',
       'quiz_participation_pct', 'final_rank', 'rank_to_submissions',
       'rank_to_quiz_participation', 'description_rate', 'archetype'],
      dtype='object')

In [32]:
df

,total_submissions,active_days_pct,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,submissions_pre_jump,submissions_post_jump,leap_size,post_jump_score_repetition,quiz_participation_pct,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate,archetype
0,4,40.0,1.000000,0.333333,0.333333,0,0.910711,0.869639,1.065738,0.041072,...,1,3,0.119495,0.418684,60.0,17,4.250000,2.428571,0.750,hardworker
1,4,30.0,1.333333,0.000000,1.000000,1,1.200012,1.112830,1.287193,0.087181,...,4,0,0.000000,0.000000,80.0,18,4.500000,2.000000,0.500,consistent_late_breakthrough
2,18,30.0,6.000000,0.000000,0.666667,0,0.561328,0.512454,0.615423,0.048873,...,2,16,0.063731,0.000000,60.0,10,0.555556,1.428571,0.667,late_joiner_dangerous
3,21,70.0,3.000000,1.333333,0.666667,3,0.592643,0.358047,2.260090,0.234596,...,8,13,1.667447,0.722339,30.0,2,0.095238,0.500000,0.810,consistent_late_breakthrough
4,27,60.0,4.500000,0.666667,1.666667,3,0.622750,0.440728,1.029055,0.182022,...,3,24,0.486757,0.006387,40.0,7,0.259259,1.400000,0.815,consistent_ai_leap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5184,17,30.0,5.666667,0.000000,5.000000,2,0.611877,0.435450,2.390095,0.176426,...,1,16,1.685680,0.000000,60.0,2,0.117647,0.285714,0.765,late_joiner_dangerous
5185,16,20.0,8.000000,0.000000,2.000000,0,0.591978,0.510059,2.118979,0.081918,...,1,15,1.380856,0.098688,50.0,7,0.437500,1.166667,0.625,late_joiner_dangerous
5186,2,20.0,1.000000,0.000000,0.000000,0,1.158344,1.122809,1.193880,0.035536,...,2,0,0.000000,0.000000,70.0,21,10.500000,2.625000,1.000,hardworker
5187,27,50.0,5.400000,5.666667,0.666667,0,1.575702,0.580214,2.410464,0.995487,...,20,7,1.816358,0.866817,50.0,16,0.592593,2.666667,0.815,ai_dump_sincere_start
5188,14,20.0,7.000000,0.000000,0.000000,0,0.587242,0.531215,2.201847,0.056027,...,1,13,1.476117,0.034786,20.0,9,0.642857,3.000000,0.500,late_joiner_dangerous

In [33]:
d2 = {'max_depth': 10, 'criterion': 'entropy', 'min_samples_split': 5, 'min_samples_leaf': 12}

d2

dt2 = DecisionTreeClassifier(**(d2))
dt2.fit(X_train, y_train, sample_weight = sample_weights)

DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_leaf=12,
                       min_samples_split=5)

In [34]:
y_pred = dt2.predict(X_test)
# display(y_pred)
f1_score_dt2 = f1_score(y_test,y_pred, average='macro')
display(f1_score_dt2)
print(classification_report(y_test, y_pred))

0.7007911340441377

              precision    recall  f1-score   support

           0       0.82      0.43      0.56       366
           1       0.95      0.95      0.95       151
           2       0.97      0.90      0.93       123
           3       0.40      0.73      0.52        51
           4       0.75      0.90      0.82        62
           5       0.13      0.39      0.20        64
           6       0.86      0.96      0.91        84
           7       0.86      0.61      0.72        93
           8       0.58      0.86      0.70        44

    accuracy                           0.68      1038
   macro avg       0.70      0.75      0.70      1038
weighted avg       0.79      0.68      0.70      1038

In [35]:
# viz_model = dtreeviz.model(
#     dt2,
#     X_train, y_train, target_name='archetype',
#     feature_names= X_train.columns.tolist(),
#     class_names= ['hardworker', 'benchmark_tweaker', 'daily_sprinter',
#            'consistent_late_breakthrough', 'low_interest_quitter',
#            'consistent_ai_leap', 'ai_dump_sincere_start',
#            'late_joiner_dangerous', 'pure_ai_quick_dump']

# )
# viz = viz_model.view()
# viz

In [37]:
# path = viz_model.view(x=X_train.iloc[0], show_just_path= True)
# path

In [38]:
# print(viz_model.explain_prediction_path(X_train.iloc[1]))

In [39]:
import joblib

joblib.dump(dt2, 'decision_tree.joblib')
joblib.dump(xgb, 'xgboost_model.joblib')

['xgboost_model.joblib']