In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline

In [10]:
df = pd.read_csv('cheating_detection_dataset_3.csv')
df
df = df.drop(columns = ['participant_id','competition_id'])
df

,total_submissions,active_days,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,user_min_score_diff,above_below_claude_min,score_time_corr,time_to_best_score_hours,quiz_participation,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate,cheated
0,22,10,2.200000,2.333333,3.000000,2,1.422391,0.643473,2.495192,0.778918,...,-0.017763,1,-0.764667,217.227229,9,16,0.727273,1.600000,0.909,0
1,10,7,1.428571,1.000000,0.666667,0,1.440718,0.571049,2.388279,0.869669,...,-0.090187,1,-0.974284,193.250851,6,12,1.200000,1.714286,0.700,1
2,17,8,2.125000,2.333333,1.000000,0,1.522378,0.585548,2.416366,0.936830,...,-0.075688,1,-0.976484,181.698905,6,13,0.764706,1.857143,0.824,0
3,16,8,2.000000,1.333333,1.333333,4,1.358629,0.619937,2.384342,0.738692,...,-0.041299,1,-0.784678,202.161856,6,14,0.875000,2.000000,0.812,0
4,33,8,4.125000,2.000000,3.666667,4,1.331861,0.551352,2.433730,0.780509,...,-0.109884,1,-0.786184,204.774922,8,10,0.303030,1.111111,0.939,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4980,29,10,2.900000,3.333333,3.000000,3,0.515016,0.426558,1.426867,0.088458,...,-0.148753,1,-0.793446,117.036404,9,6,0.206897,0.600000,0.793,0
4981,22,7,3.142857,0.333333,2.333333,3,0.736494,0.402516,2.439918,0.333978,...,-0.172796,1,-0.765788,167.503564,8,2,0.090909,0.222222,0.818,0
4982,6,2,3.000000,0.000000,0.000000,0,0.530714,0.484453,0.575788,0.046261,...,-0.090858,1,-0.821397,21.406459,3,11,1.833333,2.750000,0.833,1
4983,29,10,2.900000,2.666667,3.000000,3,0.518362,0.425564,1.397866,0.092799,...,-0.149748,1,-0.749721,99.648716,10,4,0.137931,0.363636,0.862,0
4984,7,1,7.000000,0.000000,0.000000,7,0.472861,0.417872,0.565920,0.054988,...,-0.157439,1,-0.921073,1.741780,1,3,0.428571,1.500000,0.286,1

In [11]:
df.describe()

,total_submissions,active_days,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,user_min_score_diff,above_below_claude_min,score_time_corr,time_to_best_score_hours,quiz_participation,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate,cheated
count,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,...,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000,4985.000000
mean,20.311535,6.586961,3.149178,1.460983,1.971648,2.750853,1.056498,0.595503,1.846386,0.460995,...,0.005462,0.651354,-0.762285,149.888709,5.868205,17.234102,1.747510,3.466488,0.773546,0.266800
std,12.796258,3.052922,1.340330,1.110089,1.621031,2.509875,0.423371,0.257889,0.666368,0.360551,...,0.260828,0.476589,0.305539,79.572347,2.717667,10.770775,2.616925,3.819233,0.200980,0.442332
min,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.402018,0.300000,0.488215,0.000376,...,-0.340143,0.000000,-1.000000,0.000000,0.000000,1.000000,0.013514,0.090909,0.000000,0.000000
25%,9.000000,5.000000,2.200000,0.666667,0.666667,0.000000,0.601941,0.446435,1.259200,0.096833,...,-0.144206,0.000000,-0.963970,117.151148,4.000000,8.000000,0.400000,1.222222,0.667000,0.000000
50%,19.000000,8.000000,3.000000,1.333333,1.666667,2.000000,1.068257,0.515976,2.213866,0.384490,...,-0.066068,1.000000,-0.813836,185.061568,6.000000,16.000000,0.896552,2.454545,0.838000,0.000000
75%,30.000000,9.000000,3.750000,2.333333,3.000000,4.000000,1.439786,0.652220,2.371116,0.796369,...,0.066424,1.000000,-0.700529,207.925612,8.000000,25.000000,1.869565,4.250000,0.912000,1.000000
max,74.000000,10.000000,8.000000,6.000000,9.333333,10.000000,2.243555,2.004726,2.600000,1.788525,...,1.413622,1.000000,1.000000,239.534772,10.000000,46.000000,22.500000,45.000000,1.000000,1.000000

In [12]:
df

X = df.drop(columns = ['cheated'])
y = df['cheated']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, shuffle =True)

# train_df = df.copy()
# df_0 = train_df[train_df['Diabetes_binary'] == 0]
# df_1 = train_df[train_df['Diabetes_binary'] == 1]

# df_1 = df_1.sample(len(df_0), replace = True, random_state = 42)

# train_df = pd.concat([df_0, df_1])
# train_df = train_df.sample(frac= 1, random_state = 42)
# # train_df['row_id'] = train_df.index
# # train_df.to_csv('train_NN_0p6.csv', index = False)
# # train_df = train_df.drop(columns = ['row_id'])

# X_train = train_df.drop('Diabetes_binary', axis=1)
# y_train = train_df['Diabetes_binary']
# y_train = pd.get_dummies(y_train, dtype = int).values

In [13]:
# display(X_train)
y_train = pd.DataFrame({
    'cheated' : y_train
})
train_df = pd.concat([X_train, y_train], axis = 1)
df_0 = train_df[train_df['cheated'] == 0]
df_1 = train_df[train_df['cheated'] == 1]

df_1 = df_1.sample(len(df_0), replace = True, random_state = 42)

train_df = pd.concat([df_0, df_1])
train_df = train_df.sample(frac= 1, random_state = 42)


X_train = train_df.drop('cheated', axis=1)
y_train = train_df['cheated']
# y_train = pd.get_dummies(y_train, dtype = int).values
display(X_train, y_train)
display(y_train.value_counts())

,total_submissions,active_days,submissions_per_day,submission_avg_initial_days,avg_submissions_mid,submissions_end,median_score,top_score,lowest_score,gap_median_top,...,claude_min_score,user_min_score_diff,above_below_claude_min,score_time_corr,time_to_best_score_hours,quiz_participation,final_rank,rank_to_submissions,rank_to_quiz_participation,description_rate
4832,33,10,3.300000,3.666667,3.333333,2,0.491826,0.398738,1.088063,0.093088,...,0.635006,-0.236268,1,-0.778355,160.626355,6,6,0.181818,0.857143,0.818
3515,17,6,2.833333,0.666667,0.666667,1,1.132012,0.596860,2.267516,0.535151,...,0.637326,-0.040466,1,-0.195981,163.926455,6,29,1.705882,4.142857,0.882
496,22,8,2.750000,1.000000,3.000000,0,0.876844,0.651065,2.421565,0.225779,...,0.598176,0.052889,0,-0.733488,170.803230,9,23,1.045455,2.300000,0.909
4393,10,7,1.428571,1.333333,1.000000,1,1.496386,0.689198,2.420537,0.807189,...,0.534918,0.154280,0,-0.956650,215.223984,4,19,1.900000,3.800000,0.900
2763,3,1,3.000000,0.000000,0.000000,0,0.651566,0.557292,0.736626,0.094274,...,0.612760,-0.055467,1,-0.892485,16.946229,1,23,7.666667,11.500000,0.667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,2,1,2.000000,0.000000,0.000000,0,0.523078,0.409292,0.636863,0.113785,...,0.648834,-0.239541,1,-1.000000,0.804323,1,6,3.000000,3.000000,1.000
3241,12,6,2.000000,1.000000,1.000000,6,0.900676,0.480778,2.013993,0.419898,...,0.587020,-0.106242,1,-0.995528,209.977596,5,11,0.916667,1.833333,0.333
1640,8,1,8.000000,0.000000,0.000000,0,0.503025,0.458364,0.568620,0.044661,...,0.570014,-0.111651,1,-0.859221,10.380905,0,9,1.125000,9.000000,0.875
692,14,6,2.333333,2.000000,2.000000,2,1.665968,0.464023,2.185573,1.201946,...,0.599101,-0.135078,1,-0.994095,222.391754,2,16,1.142857,5.333333,0.714
474,5,4,1.250000,0.666667,0.666667,0,1.283883,0.699182,1.418159,0.584700,...,0.598176,0.101006,0,-0.865460,139.238863,7,26,5.200000,3.250000,0.400

4832    0
3515    0
496     0
4393    0
2763    1
       ..
543     1
3241    1
1640    1
692     1
474     0
Name: cheated, Length: 5848, dtype: int64

cheated
0    2924
1    2924
Name: count, dtype: int64

In [14]:
!pip install optuna

Requirement already satisfied: optuna in c:\users\vamsi\anaconda3\lib\site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\vamsi\anaconda3\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in c:\users\vamsi\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\vamsi\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\vamsi\anaconda3\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: colorama in c:\users\vamsi\anaconda3\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\vamsi\anaconda3\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\vamsi\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\vamsi\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\vamsi\anaconda3\Lib\site-packages)

In [15]:


import optuna
from sklearn.metrics import f1_score, classification_report
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

def objective(trial):
    
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 300, 1200),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 30),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
        'gamma': trial.suggest_float('gamma', 1e-3, 5.0, log=True),
        'random_state': 42,
        'n_jobs': -1 
    }
    cv = StratifiedKFold(n_splits= 5, shuffle = True, random_state= 42)
    scores = cross_val_score(
        estimator = XGBClassifier(**param),
        X= X_train, y = y_train, cv = cv,
        scoring='f1_macro',
        n_jobs = -1
    )

    return scores.mean()

study = optuna.create_study(direction='maximize', study_name="XGBoost_CV")
study.optimize(objective, n_trials=50, show_progress_bar=True)



print(f"Best CV f1 score: {study.best_value:.4f}")
print("Best Hyperparameters:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value},")

[I 2026-07-23 12:59:42,363] A new study created in memory with name: XGBoost_CV

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-07-23 12:59:48,982] Trial 0 finished with value: 0.9481799534763983 and parameters: {'n_estimators': 414, 'max_depth': 3, 'learning_rate': 0.021494748828654278, 'subsample': 0.6602172918889491, 'colsample_bytree': 0.8952238680284063, 'min_child_weight': 1, 'reg_alpha': 0.10128955589293115, 'reg_lambda': 7.405241961351101, 'gamma': 0.008482691567579987}. Best is trial 0 with value: 0.9481799534763983.
[I 2026-07-23 12:59:55,448] Trial 1 finished with value: 0.9498879472015123 and parameters: {'n_estimators': 1101, 'max_depth': 7, 'learning_rate': 0.08916589250945005, 'subsample': 0.6278069943031808, 'colsample_bytree': 0.4324877061758517, 'min_child_weight': 8, 'reg_alpha': 0.00404081564872194, 'reg_lambda': 5.4429008632025795, 'gamma': 3.7506207677264256}. Best is trial 1 with value: 0.9498879472015123.
[I 2026-07-23 12:59:57,240] Trial 2 finished with value: 0.9427052876101272 and parameters: {'n_estimators': 991, 'max_depth': 3, 'learning_rate': 0.009349457255290896, 'subsample': 0.7989394459457406, 'colsample_bytree': 0.7477326507334332, 'min_child_weight': 19, 'reg_alpha': 0.0068821935169469765, 'reg_lambda': 0.018853983474835235, 'gamma': 0.7877626405043985}. Best is trial 1 with value: 0.9498879472015123.
[I 2026-07-23 12:59:59,646] Trial 3 finished with value: 0.9541628978279121 and parameters: {'n_estimators': 864, 'max_depth': 9, 'learning_rate': 0.009233097699875714, 'subsample': 0.5552914248297283, 'colsample_bytree': 0.9802159146033423, 'min_child_weight': 11, 'reg_alpha': 0.7496844860580756, 'reg_lambda': 2.4554209222116827, 'gamma': 0.0181007245563974}. Best is trial 3 with value: 0.9541628978279121.
[I 2026-07-23 13:00:01,870] Trial 4 finished with value: 0.9700688424085451 and parameters: {'n_estimators': 1152, 'max_depth': 5, 'learning_rate': 0.07800366401172404, 'subsample': 0.92083111729042, 'colsample_bytree': 0.9272894723256984, 'min_child_weight': 23, 'reg_alpha': 0.46881380761028685, 'reg_lambda': 0.07608374486891596, 'gamma': 0.004955138229151172}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:04,075] Trial 5 finished with value: 0.9451009575047798 and parameters: {'n_estimators': 1079, 'max_depth': 10, 'learning_rate': 0.01570111102167783, 'subsample': 0.642327163006652, 'colsample_bytree': 0.6861190793432566, 'min_child_weight': 28, 'reg_alpha': 0.012937182974238539, 'reg_lambda': 0.27429130013242303, 'gamma': 0.006369230229711817}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:05,843] Trial 6 finished with value: 0.9512538160684029 and parameters: {'n_estimators': 867, 'max_depth': 9, 'learning_rate': 0.011516900914160282, 'subsample': 0.84073205546374, 'colsample_bytree': 0.4836652757968179, 'min_child_weight': 2, 'reg_alpha': 2.4247829303289876, 'reg_lambda': 0.02903633774912832, 'gamma': 4.689212123585966}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:07,079] Trial 7 finished with value: 0.9468077190784452 and parameters: {'n_estimators': 324, 'max_depth': 10, 'learning_rate': 0.00629232476366272, 'subsample': 0.9560505789466087, 'colsample_bytree': 0.47555737906147183, 'min_child_weight': 18, 'reg_alpha': 1.9913736238770083, 'reg_lambda': 0.0023785674012451823, 'gamma': 0.1265929872151832}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:08,679] Trial 8 finished with value: 0.9563869416128649 and parameters: {'n_estimators': 803, 'max_depth': 4, 'learning_rate': 0.02823557327980965, 'subsample': 0.5412413001927411, 'colsample_bytree': 0.5215404856588713, 'min_child_weight': 15, 'reg_alpha': 0.0025500463492349676, 'reg_lambda': 1.7202540004074087, 'gamma': 0.0018853002655405031}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:09,691] Trial 9 finished with value: 0.9533077737863709 and parameters: {'n_estimators': 391, 'max_depth': 4, 'learning_rate': 0.09343739998567474, 'subsample': 0.5127637074333831, 'colsample_bytree': 0.47977030070799315, 'min_child_weight': 20, 'reg_alpha': 0.2001761407268618, 'reg_lambda': 0.03325878405876107, 'gamma': 0.005773664811218603}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:10,756] Trial 10 finished with value: 0.9367162110945413 and parameters: {'n_estimators': 638, 'max_depth': 6, 'learning_rate': 0.04496556212671551, 'subsample': 0.4051982179424297, 'colsample_bytree': 0.6511816887144104, 'min_child_weight': 28, 'reg_alpha': 6.423785841954956, 'reg_lambda': 0.0011184657131865143, 'gamma': 0.08415492453572528}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:13,197] Trial 11 finished with value: 0.963912601381019 and parameters: {'n_estimators': 1195, 'max_depth': 5, 'learning_rate': 0.03332651081025836, 'subsample': 0.9436256752836181, 'colsample_bytree': 0.8044953294231226, 'min_child_weight': 24, 'reg_alpha': 0.04245610218668476, 'reg_lambda': 0.4474139432724771, 'gamma': 0.0012712814806640016}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:15,561] Trial 12 finished with value: 0.9673324816304827 and parameters: {'n_estimators': 1187, 'max_depth': 6, 'learning_rate': 0.053755628390592815, 'subsample': 0.9928174407083499, 'colsample_bytree': 0.8361614865926374, 'min_child_weight': 24, 'reg_alpha': 0.04987084874375322, 'reg_lambda': 0.2936175938353164, 'gamma': 0.0011586046946736941}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:17,818] Trial 13 finished with value: 0.9688715555713754 and parameters: {'n_estimators': 1154, 'max_depth': 7, 'learning_rate': 0.0559003973345355, 'subsample': 0.9930483243887056, 'colsample_bytree': 0.8955794633431363, 'min_child_weight': 24, 'reg_alpha': 0.2931700630792724, 'reg_lambda': 0.14867991343831982, 'gamma': 0.0011462565286235852}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:19,937] Trial 14 finished with value: 0.9669904509202745 and parameters: {'n_estimators': 993, 'max_depth': 7, 'learning_rate': 0.061124971606288235, 'subsample': 0.8413164555632469, 'colsample_bytree': 0.9801597246926409, 'min_child_weight': 24, 'reg_alpha': 0.4005375598846926, 'reg_lambda': 0.08746779529905956, 'gamma': 0.028118107722978288}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:22,258] Trial 15 finished with value: 0.9642565202645385 and parameters: {'n_estimators': 1018, 'max_depth': 7, 'learning_rate': 0.06813492610473436, 'subsample': 0.9133308663100048, 'colsample_bytree': 0.9069813359269678, 'min_child_weight': 30, 'reg_alpha': 0.7538332670913885, 'reg_lambda': 0.009919726696313247, 'gamma': 0.003321005499296731}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:24,589] Trial 16 finished with value: 0.9519427500768665 and parameters: {'n_estimators': 1195, 'max_depth': 8, 'learning_rate': 0.0445659228129605, 'subsample': 0.749768330444264, 'colsample_bytree': 0.8818707097110694, 'min_child_weight': 22, 'reg_alpha': 9.105638161682439, 'reg_lambda': 0.13188547420413227, 'gamma': 0.02292029407331712}. Best is trial 4 with value: 0.9700688424085451.
[I 2026-07-23 13:00:26,498] Trial 17 finished with value: 0.9712657845106054 and parameters: {'n_estimators': 733, 'max_depth': 5, 'learning_rate': 0.033549292929657866, 'subsample': 0.8942092569770366, 'colsample_bytree': 0.9945787991994351, 'min_child_weight': 13, 'reg_alpha': 0.17975725538800627, 'reg_lambda': 0.8728843709210815, 'gamma': 0.0034490581592856897}. Best is trial 17 with value: 0.9712657845106054.
[I 2026-07-23 13:00:28,319] Trial 18 finished with value: 0.9700683476682675 and parameters: {'n_estimators': 590, 'max_depth': 5, 'learning_rate': 0.03217250694572656, 'subsample': 0.8900109079535158, 'colsample_bytree': 0.9712367709816943, 'min_child_weight': 12, 'reg_alpha': 0.040042454886330084, 'reg_lambda': 0.7556155450342271, 'gamma': 0.059035960447788985}. Best is trial 17 with value: 0.9712657845106054.
[I 2026-07-23 13:00:30,788] Trial 19 finished with value: 0.9728080227179321 and parameters: {'n_estimators': 692, 'max_depth': 5, 'learning_rate': 0.02219015327859149, 'subsample': 0.7429928053304675, 'colsample_bytree': 0.808541112170075, 'min_child_weight': 5, 'reg_alpha': 0.11634026823820011, 'reg_lambda': 1.1755597093973065, 'gamma': 0.23564978897709785}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:32,538] Trial 20 finished with value: 0.9652815452310088 and parameters: {'n_estimators': 667, 'max_depth': 4, 'learning_rate': 0.020022486298894672, 'subsample': 0.7320256137899376, 'colsample_bytree': 0.5956165436100501, 'min_child_weight': 6, 'reg_alpha': 0.0011693240315734175, 'reg_lambda': 1.3507722036301322, 'gamma': 0.3872194994754605}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:35,661] Trial 21 finished with value: 0.9693861857211908 and parameters: {'n_estimators': 529, 'max_depth': 5, 'learning_rate': 0.023915780757842404, 'subsample': 0.856593025960582, 'colsample_bytree': 0.7838323588443392, 'min_child_weight': 5, 'reg_alpha': 0.12401931503107227, 'reg_lambda': 0.8889554000044904, 'gamma': 0.3517615337514286}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:38,576] Trial 22 finished with value: 0.9608323962898375 and parameters: {'n_estimators': 782, 'max_depth': 6, 'learning_rate': 0.014001172491245955, 'subsample': 0.7651338801759161, 'colsample_bytree': 0.9374623651825075, 'min_child_weight': 13, 'reg_alpha': 0.7820125642093622, 'reg_lambda': 3.0457513936599225, 'gamma': 1.095024742987155}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:40,958] Trial 23 finished with value: 0.9712658508902644 and parameters: {'n_estimators': 716, 'max_depth': 5, 'learning_rate': 0.039190850078708366, 'subsample': 0.7056234612017216, 'colsample_bytree': 0.8410926432545871, 'min_child_weight': 9, 'reg_alpha': 0.01875241477187518, 'reg_lambda': 0.06106834103959673, 'gamma': 0.012102415721196991}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:42,997] Trial 24 finished with value: 0.9717793352949616 and parameters: {'n_estimators': 723, 'max_depth': 4, 'learning_rate': 0.039136282579441344, 'subsample': 0.6941594571296007, 'colsample_bytree': 0.735517128067213, 'min_child_weight': 9, 'reg_alpha': 0.019144526224558915, 'reg_lambda': 0.007276360759539697, 'gamma': 0.013932700877134342}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:44,356] Trial 25 finished with value: 0.9700681998531909 and parameters: {'n_estimators': 570, 'max_depth': 4, 'learning_rate': 0.040751808933085935, 'subsample': 0.6734890651617331, 'colsample_bytree': 0.7343689881071267, 'min_child_weight': 8, 'reg_alpha': 0.01806564471333313, 'reg_lambda': 0.006082764217988681, 'gamma': 0.010730380111557006}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:46,446] Trial 26 finished with value: 0.9608333972749531 and parameters: {'n_estimators': 704, 'max_depth': 3, 'learning_rate': 0.019063975770275778, 'subsample': 0.7156125500590914, 'colsample_bytree': 0.8411719026272084, 'min_child_weight': 4, 'reg_alpha': 0.018752679649264876, 'reg_lambda': 0.00400929777199389, 'gamma': 0.05298789004681085}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:47,893] Trial 27 finished with value: 0.970241148369691 and parameters: {'n_estimators': 497, 'max_depth': 6, 'learning_rate': 0.028435552869897792, 'subsample': 0.6970835474816909, 'colsample_bytree': 0.6930552467902524, 'min_child_weight': 9, 'reg_alpha': 0.07743950892517726, 'reg_lambda': 0.009737847565882337, 'gamma': 0.18796567658734295}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:50,061] Trial 28 finished with value: 0.9700668268797076 and parameters: {'n_estimators': 885, 'max_depth': 4, 'learning_rate': 0.040365552586994334, 'subsample': 0.5782551759287773, 'colsample_bytree': 0.6249280252086151, 'min_child_weight': 10, 'reg_alpha': 0.02442155413540529, 'reg_lambda': 0.047830900900563314, 'gamma': 0.014642576599251396}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:51,344] Trial 29 finished with value: 0.9533115754384041 and parameters: {'n_estimators': 468, 'max_depth': 3, 'learning_rate': 0.02369806017654225, 'subsample': 0.7894743139224679, 'colsample_bytree': 0.7615446145989427, 'min_child_weight': 1, 'reg_alpha': 0.008965602349767735, 'reg_lambda': 9.895871175434683, 'gamma': 0.035335228039962835}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:53,435] Trial 30 finished with value: 0.9570711264342592 and parameters: {'n_estimators': 798, 'max_depth': 3, 'learning_rate': 0.016774392429413334, 'subsample': 0.6073345705676515, 'colsample_bytree': 0.8381464726254004, 'min_child_weight': 7, 'reg_alpha': 0.08416469130853936, 'reg_lambda': 0.0011717299034923923, 'gamma': 2.0974596814231026}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:55,443] Trial 31 finished with value: 0.9627164003390007 and parameters: {'n_estimators': 712, 'max_depth': 5, 'learning_rate': 0.03396010202351385, 'subsample': 0.6732371476096861, 'colsample_bytree': 0.7230116573791839, 'min_child_weight': 15, 'reg_alpha': 0.20322355539637987, 'reg_lambda': 4.188096538991242, 'gamma': 0.002805201479245237}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:57,469] Trial 32 finished with value: 0.9676747391007096 and parameters: {'n_estimators': 759, 'max_depth': 5, 'learning_rate': 0.02627504997699269, 'subsample': 0.8032641052252878, 'colsample_bytree': 0.8669626522558288, 'min_child_weight': 14, 'reg_alpha': 0.005057745835581498, 'reg_lambda': 0.5325087044608371, 'gamma': 0.012424966845055927}. Best is trial 19 with value: 0.9728080227179321.
[I 2026-07-23 13:00:59,670] Trial 33 finished with value: 0.9755409227515388 and parameters: {'n_estimators': 641, 'max_depth': 4, 'learning_rate': 0.04717866710517581, 'subsample': 0.6174166874607695, 'colsample_bytree': 0.7881402181920016, 'min_child_weight': 4, 'reg_alpha': 0.14565293209669603, 'reg_lambda': 0.2454545180435277, 'gamma': 0.003611403782847257}. Best is trial 33 with value: 0.9755409227515388.
[I 2026-07-23 13:01:01,981] Trial 34 finished with value: 0.9760560591868732 and parameters: {'n_estimators': 630, 'max_depth': 4, 'learning_rate': 0.04864393854744345, 'subsample': 0.6113684047331296, 'colsample_bytree': 0.7980799641046714, 'min_child_weight': 4, 'reg_alpha': 0.030928460559802962, 'reg_lambda': 0.19859062757302348, 'gamma': 0.006762252765367105}. Best is trial 34 with value: 0.9760560591868732.
[I 2026-07-23 13:01:03,910] Trial 35 finished with value: 0.9760560591704287 and parameters: {'n_estimators': 635, 'max_depth': 4, 'learning_rate': 0.07066467598526305, 'subsample': 0.6017209181125638, 'colsample_bytree': 0.7971501671637986, 'min_child_weight': 3, 'reg_alpha': 0.0677719228483065, 'reg_lambda': 0.21603629381815972, 'gamma': 0.002302841605424738}. Best is trial 34 with value: 0.9760560591868732.
[I 2026-07-23 13:01:05,576] Trial 36 finished with value: 0.974002592761865 and parameters: {'n_estimators': 643, 'max_depth': 3, 'learning_rate': 0.08180980591800158, 'subsample': 0.48456319307767837, 'colsample_bytree': 0.7984453294397752, 'min_child_weight': 3, 'reg_alpha': 0.09677021550330471, 'reg_lambda': 0.2377004210410367, 'gamma': 0.002256646973922853}. Best is trial 34 with value: 0.9760560591868732.
[I 2026-07-23 13:01:07,241] Trial 37 finished with value: 0.9762265637027456 and parameters: {'n_estimators': 613, 'max_depth': 3, 'learning_rate': 0.07840251058379538, 'subsample': 0.4596307270397224, 'colsample_bytree': 0.7841279302260321, 'min_child_weight': 3, 'reg_alpha': 0.03951533884011991, 'reg_lambda': 0.16736718273037932, 'gamma': 0.0022195468636567483}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:08,637] Trial 38 finished with value: 0.9757144529196153 and parameters: {'n_estimators': 597, 'max_depth': 3, 'learning_rate': 0.0688831360208446, 'subsample': 0.4484685265087524, 'colsample_bytree': 0.6897257752965293, 'min_child_weight': 1, 'reg_alpha': 0.05260578388736772, 'reg_lambda': 0.13439315591960796, 'gamma': 0.0068826226645358176}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:10,202] Trial 39 finished with value: 0.9736607868141369 and parameters: {'n_estimators': 570, 'max_depth': 3, 'learning_rate': 0.07131969498142153, 'subsample': 0.4463660030893646, 'colsample_bytree': 0.5745160384900291, 'min_child_weight': 2, 'reg_alpha': 0.058091809090063944, 'reg_lambda': 0.137596660565301, 'gamma': 0.00589058455213645}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:11,386] Trial 40 finished with value: 0.9746870465379963 and parameters: {'n_estimators': 443, 'max_depth': 3, 'learning_rate': 0.098197226206357, 'subsample': 0.47081759015567604, 'colsample_bytree': 0.6779193476752202, 'min_child_weight': 1, 'reg_alpha': 0.03368308903649389, 'reg_lambda': 0.020981517053288032, 'gamma': 0.007122464360294368}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:13,154] Trial 41 finished with value: 0.9750284977874845 and parameters: {'n_estimators': 599, 'max_depth': 4, 'learning_rate': 0.04995241392898711, 'subsample': 0.6123785735703814, 'colsample_bytree': 0.7661052529275085, 'min_child_weight': 3, 'reg_alpha': 0.01200135798268351, 'reg_lambda': 0.22153639882563836, 'gamma': 0.004116096444972972}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:14,255] Trial 42 finished with value: 0.97006727565768 and parameters: {'n_estimators': 527, 'max_depth': 3, 'learning_rate': 0.06450995112231249, 'subsample': 0.5543685311994586, 'colsample_bytree': 0.703513202281675, 'min_child_weight': 4, 'reg_alpha': 0.06360260508652832, 'reg_lambda': 0.41237280642298213, 'gamma': 0.0018302532831107811}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:15,943] Trial 43 finished with value: 0.9736601752022089 and parameters: {'n_estimators': 628, 'max_depth': 4, 'learning_rate': 0.08008242453409663, 'subsample': 0.5178535649547562, 'colsample_bytree': 0.7735275194048973, 'min_child_weight': 7, 'reg_alpha': 0.02873310181116142, 'reg_lambda': 0.09032153498218246, 'gamma': 0.0020547539865332573}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:16,886] Trial 44 finished with value: 0.9736607041549906 and parameters: {'n_estimators': 366, 'max_depth': 4, 'learning_rate': 0.05735664502479993, 'subsample': 0.5848005504673243, 'colsample_bytree': 0.6577365696898061, 'min_child_weight': 3, 'reg_alpha': 0.007745963901067104, 'reg_lambda': 0.15596562310911186, 'gamma': 0.008552971842075053}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:18,002] Trial 45 finished with value: 0.9731473241428696 and parameters: {'n_estimators': 526, 'max_depth': 3, 'learning_rate': 0.07465707971422837, 'subsample': 0.4027914507866564, 'colsample_bytree': 0.4072531119251057, 'min_child_weight': 1, 'reg_alpha': 0.13180235084763348, 'reg_lambda': 0.349218680537591, 'gamma': 0.004212104258275143}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:20,392] Trial 46 finished with value: 0.9741725867550141 and parameters: {'n_estimators': 838, 'max_depth': 4, 'learning_rate': 0.05025802777696089, 'subsample': 0.6488601400401705, 'colsample_bytree': 0.7152564664191909, 'min_child_weight': 5, 'reg_alpha': 0.2778635102851015, 'reg_lambda': 0.042632102820348086, 'gamma': 0.001527791124880197}. Best is trial 37 with value: 0.9762265637027456.
[I 2026-07-23 13:01:22,090] Trial 47 finished with value: 0.9736620937911231 and parameters: {'n_estimators': 663, 'max_depth': 3, 'learning_rate': 0.08721449098142829, 'subsample': 0.44706166547261716, 'colsample_bytree': 0.8126067070764406, 'min_child_weight': 6, 'reg_alpha': 0.047257666943578004, 'reg_lambda': 0.19428162940506105, 'gamma': 0.0027698071924208193}. Best is trial 37 with value: 0.9762265637027456.

In [16]:
xgb = XGBClassifier(**(study.best_params))
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7841279302260321, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=0.0022195468636567483, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.07840251058379538, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=3, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=613, n_jobs=None,
              num_parallel_tree=None, ...)

In [17]:
y_pred = xgb.predict(X_test)
f1_score = f1_score(y_test,y_pred, average='macro')
display(f1_score)
print(classification_report(y_test, y_pred))

0.9301059355039726

              precision    recall  f1-score   support

           0       0.96      0.97      0.96       731
           1       0.91      0.88      0.90       266

    accuracy                           0.95       997
   macro avg       0.93      0.93      0.93       997
weighted avg       0.95      0.95      0.95       997

In [18]:
importance = pd.DataFrame({
    'Feature' : X_train.columns,
    'Importance' : xgb.feature_importances_
})

importance = importance.sort_values(by = 'Importance', ascending= False)
display(importance)

                        Feature  Importance
1                   active_days    0.221932
18              score_time_corr    0.148896
8                  lowest_score    0.095019
14       top_score_on_peak_hour    0.078608
20           quiz_participation    0.066837
7                     top_score    0.039383
0             total_submissions    0.037043
3   submission_avg_initial_days    0.035622
16          user_min_score_diff    0.028372
4           avg_submissions_mid    0.025857
9                gap_median_top    0.024828
19     time_to_best_score_hours    0.022831
10               gap_lowest_top    0.021998
24             description_rate    0.020078
6                  median_score    0.018031
2           submissions_per_day    0.017932
13    peak_submissions_per_hour    0.014677
12        top_score_on_peak_day    0.012700
5               submissions_end    0.012295
11     peak_submissions_per_day    0.012265
21                   final_rank    0.012073
15             claude_min_score    0.011207
23   rank_to_quiz_participation    0.011024
22          rank_to_submissions    0.010495
17       above_below_claude_min    0.000000

In [ ]:
# def objective(trial):
    
#     param = {
#         'n_estimators': trial.suggest_int('n_estimators', 300, 1200),
#         'max_depth': trial.suggest_int('max_depth', 3, 10),
#         'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
#         'subsample': trial.suggest_float('subsample', 0.4, 1.0),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
#         'min_child_weight': trial.suggest_int('min_child_weight', 1, 30),
#         'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
#         'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
#         'gamma': trial.suggest_float('gamma', 1e-3, 5.0, log=True),
#         'random_state': 42,
#         'n_jobs': -1 
#     }
#     cv = StratifiedKFold(n_splits= 5, shuffle = True, random_state= 42)
#     scores = cross_val_score(
#         estimator = XGBClassifier(**param),
#         X= X_train, y = y_train, cv = cv,
#         scoring='f1_macro',
#         n_jobs = -1
#     )

#     return scores.mean()

# study = optuna.create_study(direction='maximize', study_name="XGBoost_CV")
# study.optimize(objective, n_trials=50, show_progress_bar=True)



# print(f"Best CV f1 score: {study.best_value:.4f}")
# print("Best Hyperparameters:")
# for key, value in study.best_params.items():
#     print(f"    '{key}': {value},")